language: python
python:
- 3.6
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: NZG3eLbmNqijT3bbR1ZtsvK3j3Bk+G+Nkxg6JSkhrMRAH3KDPL1xQV+V8DW/7vnMfqELKaYsEoAohXU63/53MY3RlJKGPO71aGCPJynQRCq26VMl+AtFWijJ7bfv8GZNAqEJpa8CpuvOStX/O/WHM3AJ5avSDQkVlkvEOZvpSSmorQ0Gftb+jQHGK5DYqdkoEtil4JdABOv3feQ/hxPPMKG/duiqmeqnF7ELXmKSwhQJMTJZz0+uxrL6UEyyPY/2HNKHABU957/0PPRoPKgSUPsA1h4aNnfYuXz4c4PTo8coMNHx3N7FuApRjA5ByL/PIVnDkbDJJUx4dqByKD6DaZt5+6+4atCcUl9KQksHpS0PcRMjW1iseWm1j0Y8OcipM/FI+5IKZ6ZFDzRoFrepXcYwMREFWeMKudwqLYGE8x8lTQbBIpnRXg42hLoWvgNcLoBG1NxDMt75K3GfgJViSgcwt8WCNxSrgYC/UGqhkqJZu4aM+LDrOT9aLYBf7XvpHBN4bhp5ARLF/ApZH2zDpqdFJ4fa/DTDf4jS+TGGEEXlZIbCYSEazqrePmVjeezY6CaMHh1i4UsiViUmLsZyRnuTxM05DvAPqWmGXADrpxReLpMxkDrjYw3YE4hiYx5cPCzasrnkFIdyL3WUES/9xLtKxfeOBKn7Y1EkcVWkgfA=
  on:
    tags: true
    repo: davidemoro/play_cassandra
    python: 3.6
